---
title: "Project 01 - Data 607"
output: html_document
date: "2024-02-18"
Author Name : Syed Hasan
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(lubridate)
```

#Problem 1 :

```{r, echo=FALSE}

theUrl <- 'https://raw.githubusercontent.com/SyedHasanMafi/Data-607/main/tournamentinfo.txt'

dfTournament <- read_csv(file = theUrl,col_names = FALSE)

head(dfTournament)

tail(dfTournament)

```

```{r, echo=FALSE}
mTournament <- matrix(unlist(dfTournament), byrow=TRUE)

m1 <- mTournament[seq(5,length(mTournament),3)]
head(m1)
```



```{r, echo=FALSE}
m2 <- mTournament[seq(6,length(mTournament),3)]
head(m2)
```


```{r, echo=FALSE}
# matching first numbers
ID <- as.numeric(str_extract(m1, '\\d+'))

# matching the first combination of a letter, any amount of characters and "|"
Name <- str_extract(m1, '[A-z].{1,32}') 

# extracting the name
Name <- str_trim(str_extract(Name, '.+\\s{2,}'))

# matching the first two letters (state) in the second matrix 
State <- str_extract(m2, '[A-Z]{2}') 

# matching at least 1 number, a period, and 1 number
TotalNumberofPoints <- as.numeric(str_extract(m1, '\\d+\\.\\d'))

# matching the combination of "R", any characters and "-"
PreRating <- str_extract(m2, 'R:.{8,}-')

# matching first 4 numbers
PreRating <- as.numeric(str_extract(PreRating, '\\d{1,4}'))

# matching all combinations of 1 letter 2 spaces and any numbers
Rounds <- str_extract_all(m1, '[A-Z]\\s{2,}\\d+')

# matching numbers
Rounds <- str_extract_all(Rounds, '\\d+')
```

```{r, echo=FALSE}
AvgOppPreChessRating <- c()

for(i in c(1:length(Rounds))){
  AvgOppPreChessRating[i] <- round(mean(PreRating[as.numeric(Rounds[[i]])]),0)
}
AvgOppPreChessRating

```


```{r, echo=FALSE}

Project1 <- data.frame(ID,Name,State,TotalNumberofPoints,PreRating,AvgOppPreChessRating)

head(Project1)
```


```{r, echo=FALSE}
csv_df = read_csv('https://raw.githubusercontent.com/SyedHasanMafi/Data-607/main/tournamentinfo.txt')
```


```{r, echo=FALSE}
csv_df
```